### ISSUE TITLE
[Backend] Reviews list view

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/com_jed4#13]
Columns:
- Title
- Date
- Extension
- User
- Published State
- IP Address - linked to Review Detective

Filters - saved in session:
- Title 
- Extension
- User
- Published State
- IP Address
- Open search field

All columns are orderable, and ordering is saved into the session. Pagination should not use AJAX.

Default ordering: 
- Most recent first

**Comment by roland-d** [comment]
Merged with commit 9cc5170b29bbcf8192e81b0c4fa51dbb9da3158c
